trigger:
  branches:
    include:
      - main

pool:
  name: OnPremWin
  vmImage: 'ubuntu-latest'

variables:
- name: container_registry
  value: DevOps2AzContainerRegistry-go2cloud
- name: repository
  value: internal/azurenamingtool

steps:
  - task: CmdLine@2
    displayName: 'Install emulator'
    inputs:
      script: 'sudo apt-get install -y qemu qemu-user-static'

  - task: Docker@2
    displayName: 'Login'
    inputs:
      containerRegistry: $(container_registry)
      command: 'login'

  - task: Docker@2
    displayName: 'Build'
    inputs:
      containerRegistry: $(container_registry)
      repository: $(repository)
      command: 'build'
      arguments: '--platform linux/arm64'
      Dockerfile: 'Dockerfile'
      tags: 'latest'

  - task: Docker@2
    displayName: 'Push'
    inputs:
      containerRegistry: $(container_registry)
      repository: $(repository)
      command: 'push'
      tags: 'latest'