trigger:
  branches:
    include:
      - main

pool:
  name: OnPremUX
  vmImage: 'ubuntu-latest'

variables:
- name: container_registry
  value: DevOps2AzContainerRegistrySPN-go2cloud
- name: repository
  value: internal/azurenamingtool

jobs:
- job: CreateDockerContainer
  steps:
    # - task: CmdLine@2
    #   displayName: 'Install emulator'
    #   inputs:
    #     script: 'sudo apt-get install -y qemu-system qemu-user-static'

    - task: Docker@2
      displayName: 'Login'
      inputs:
        containerRegistry: $(container_registry)
        command: 'login'

    # - task: Docker@2
    #   displayName: 'Build'
    #   inputs:
    #     containerRegistry: $(container_registry)
    #     repository: $(repository)
    #     command: 'build'
    #     arguments: '--platform linux/arm64'
    #     Dockerfile: '**/src/Dockerfile'
    #     tags: 'latest'

    # - task: PowerShell@2
    #   displayName: 'Set up Docker Buildx and QEMU'
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    #       docker buildx create --name mybuilder --driver docker-container --use
    #       docker buildx inspect --bootstrap

    - task: Bash@3
      displayName: 'Run buildx'
      inputs:
        workingDirectory: './src'
        targetType: inline
        script: |
          docker buildx build --platform linux/amd64,linux/arm64 .

    - task: Docker@2
      displayName: 'Push'
      inputs:
        containerRegistry: $(container_registry)
        repository: $(repository)
        command: 'push'
        tags: 'latest'